services:
  clojure:
    image: clojure:latest
    volumes:
      - .:/usr/src/app
      - m2:/root/.m2
      - gitlibs:/root/.gitlibs
    working_dir: /usr/src/app
    ports:
      - 5555:5555
      - 8080:8080
    entrypoint: >
      sh -c "clojure -M:nrepl"]

volumes:
  m2:
    external: true
  gitlibs:
    external: true
